### ISSUE TITLE
Crash with CSS Gradients: `TypeError: i.walkFunctionNodes is not a function`

### ISSUE THREAD

**Issue by rotu** [timreichen/Bundler#54]
When I try to run bundler on the below HTML, I get the error `TypeError: i.walkFunctionNodes is not a function`

> deno run -A --unstable https://deno.land/x/bundler/cli.ts bundle test.html
> Entry test.html
> TypeError: i.walkFunctionNodes is not a function
>     at <input css v_vlzn>:2:10
>     at https://cdn.esm.sh/v53/postcss-double-position-gradients@1.0.0/deno/postcss-double-position-gradients.js:2:313
>     at https://cdn.esm.sh/v53/postcss@8.3.5/deno/postcss.js:23:1632
>     at https://cdn.esm.sh/v53/postcss@8.3.5/deno/postcss.js:23:1326
>     at z.each (https://cdn.esm.sh/v53/postcss@8.3.5/deno/postcss.js:23:1194)
>     at z.walk (https://cdn.esm.sh/v53/postcss@8.3.5/deno/postcss.js:23:1301)
>     at https://cdn.esm.sh/v53/postcss@8.3.5/deno/postcss.js:23:1392
>     at R.each (https://cdn.esm.sh/v53/postcss@8.3.5/deno/postcss.js:23:1194)
>     at R.walk (https://cdn.esm.sh/v53/postcss@8.3.5/deno/postcss.js:23:1301)
>     at R.walkDecls (https://cdn.esm.sh/v53/postcss@8.3.5/deno/postcss.js:23:1593)
>     at Object.plugin (https://cdn.esm.sh/v53/postcss-double-position-gradients@1.0.0/deno/postcss-double-position-gradients.js:2:250)

```html
<!DOCTYPE html>

<html lang="en">
	<head>
		<style>
		body { background-image: linear-gradient(black, white); }
		</style>
	</head>
<body></body>
</html>
```

**Comment by timreichen** [comment]
fixed with the restructure. Closing the issue.

**Comment by rotu** [comment]
@timreichen
Is this really working for you? I seem to still have a problem with PostCSS:

> error: Import 'https://esm.sh/v86/postcss-nesting@7.0.1/deno/postcss-nesting.js' failed: 500 Internal Server Error
>     at https://esm.sh/v86/postcss-preset-env@6.7.0/deno/postcss-preset-env.js:2:2086

**Comment by rotu** [comment]
nevermind. This new issue is reported here https://github.com/timreichen/Bundler/issues/56#issue-1268324879
